app/urls.py
from django.urls import path
from . import views

app_name = 'app'

urlpatterns = [
    path('', views.home, name='home'),
    path('portale-internetowe/', views.portal, name='portal'),
    path('sklepy-internetowe/', views.shop, name='shop'),
    path('strony-wizytowki/', views.on_page_website, name='on_page_website'),
    path('e-marketing/', views.e_marketing, name='e_marketing'),
    path('kontakt/', views.contact, name='contact'),
    path('wycena-online/', views.valuation_online, name='valuation'),
    path('polityka-prywatnosci/', views.privacy_policy, name='privacy_policy'),
    path('opinie/', views.reviews, name='reviews'),
]

app_rama/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('tinymce/', include('tinymce.urls')),
    path('', include('app.urls', namespace='app')),
    path('newsletter/', include('blog.urls', namespace='blog')),
    path('realizacje/', include('realization.urls', namespace='realization')),
    path('en/', include('en_app.urls', namespace='en_app')),
    path('en/newsletter/', include('en_blog.urls', namespace='en_blog')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('en/work/', include('en_realization.urls', namespace='en_realization')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.post_list, name='post_list'),
    path('<slug:slug>/', views.single_post, name='single_post')
]

en_app/urls.py
from django.urls import path
from . import views

app_name = 'en_app'

urlpatterns = [
    path('', views.home, name='home'),
]

realization/urls.py
from django.urls import path
from . import views

app_name = 'realization'

urlpatterns = [
    path('', views.home, name='home'),
    path('<slug:slug>/', views.realization, name='realization'),
]

en_app/models.py
from django.db import models

# Create your models here.

en_app/views.py
from django.shortcuts import render
from en_blog.models import Category, Post


def home(request):
    #must by
    category = Category.objects.all()
    try:
        category_1 = category[0]
    except:
        category_1 = 'Dla nowicjuszy'
    try:
        category_2 = category[1]
    except:
        category_2 = 'Technologie'
    try:
        category_3 = category[2]
    except:
        category_3 = 'Realizacje'
    try:
        category_4 = category[3]
    except:
        category_4 = 'Promocja'
    post_category_1 = Post.objects.filter(category=category_1)[:5]
    post_category_2 = Post.objects.filter(category=category_2)[:2]
    post_category_3 = Post.objects.filter(category=category_3)[:3]
    post_category_4 = Post.objects.filter(category=category_4)[:3]
    #get newsleter footer
    best_news = Post.objects.all().order_by('order_number_home_page')[:5]
    try:
        best_news_1 = best_news[0]
    except:
        best_news_1 = None
    try:
        best_news_2 = best_news[1]
    except:
        best_news_2 = None
    try:
        best_news_3 = best_news[2]
    except:
        best_news_3 = None
    try:
        best_news_4 = best_news[3]
    except:
        best_news_4 = None
    try:
        best_news_5 = best_news[4]
    except:
        best_news_5 = None


    context = {'category_1': category_1,
               'category_2': category_2,
               'category_3': category_3,
               'category_4': category_4,
               'post_category_1': post_category_1,
               'post_category_2': post_category_2,
               'post_category_3': post_category_3,
               'post_category_4': post_category_4,
               'best_news_1': best_news_1,
               'best_news_2': best_news_2,
               'best_news_3': best_news_3,
               'best_news_4': best_news_4,
               'best_news_5': best_news_5,
               'best_news': best_news,
               }
    return render(request, 'en_app/home.html', context)

en_app/templates/en_app/basic/footer.html
{% load static %}
  <footer class="bg-dark">
    <div class="container space-2">
      <div class="row mb-7">
        <div class="col-lg-3 mb-5 mb-lg-0">
          <!-- Logo -->
          <a href="{% url 'app:home' %}" aria-label="TG Website">
		        <img class="navbar-left" style="max-width:240px; margin-top: -0px;" src="{% static 'assets/img/logos/front-logo-white-5.png' %}" alt="Logo TG Website">
          </a>
        </div>

        <div class="col-6 col-lg-2 mb-5 mb-lg-0">
          <h4 class="h6 text-white font-weight-medium">Website map</h4>
          <ul class="list-unstyled font-size-1">
            <li class="py-2"><a class="text-white-70" href="{% url 'app:home' %}">Home</a></li>
            <li class="py-2"><a class="text-white-70" href="{% url 'realization:home' %}">Work</a></li>
            <li class="py-2"><a class="text-white-70" href="{% url 'blog:post_list' %}">Opinions&nbsp;&&nbsp;References</a></li>
            <li class="py-2"><a class="text-white-70" href="{% url 'app:contact' %}">Contact</a></li>
          </ul>
        </div>

        <div class="col-6 col-lg-2 mb-5 mb-lg-0">
          <h4 class="h6 text-white font-weight-medium">Offer</h4>
          <ul class="list-unstyled font-size-1">
            <li class="py-2"><a class="text-white-70" href="{% url 'app:portal' %}">Internet portals</a></li>
            <li class="py-2"><a class="text-white-70" href="{% url 'app:shop' %}">Internet shops</a></li>
            <li class="py-2"><a class="text-white-70" href="{% url 'app:on_page_website' %}">One-page websites</a></li>
            <li class="py-2"><a class="text-white-70" href="{% url 'app:e_marketing' %}">E-marketing</a></li>
          </ul>
        </div>

        <div class="col-lg-5">
          <h4 class="h6 text-white font-weight-medium">Our newsletter</h4>
          <ul class="list-unstyled font-size-1">
            {% for post in best_news %}
            <li class="py-2"><a class="text-white-70" href="{% url 'blog:single_post' post.slug %}">{{ post.title|truncatechars:50 }}</a></li>
            {% endfor %}
          </ul>
        </div>
      </div>

    </div>
  </footer>

en_app/templates/en_app/basic/navbar.html
{% load static %}
        <!-- Nav -->
        <nav class="js-mega-menu navbar navbar-expand-md u-header__navbar u-header__navbar--no-space">
          <!-- Logo -->
          <a href="{% url 'en_app:home' %}" aria-label="TG Website">
		        <img class="navbar-left" style="max-width:240px; margin-top: -0px;" src="{% static 'assets/img/logos/front-logo-5.png' %}" alt="TG Website Logo">
          </a>
          <!-- End Logo -->

          <!-- Responsive Toggle Button -->
          <button type="button" class="navbar-toggler btn u-hamburger"
                  aria-label="Toggle navigation"
                  aria-expanded="false"
                  aria-controls="navBar"
                  data-toggle="collapse"
                  data-target="#navBar">
            <span id="hamburgerTrigger" class="u-hamburger__box">
              <span class="u-hamburger__inner"></span>
            </span>
          </button>
          <!-- End Responsive Toggle Button -->

          <div id="navBar" class="collapse navbar-collapse u-header__navbar-collapse">
            <ul class="navbar-nav u-header__navbar-nav">

              <!-- Reference -->
              <li class="nav-item u-header__nav-item">
                <a class="nav-link u-header__nav-link" href="{% url 'en_realization:home' %}">Work</a>
              </li>
              <!-- End Reference -->
              
              <!-- Reference -->
              <li class="nav-item u-header__nav-item">
                <a class="nav-link u-header__nav-link" href="{% url 'app:reviews' %}">Reviews</a>
              </li>
              <!-- End Reference -->
              
              <!-- Docs -->
              <li class="nav-item hs-has-mega-menu u-header__nav-item"
                  data-event="hover"
                  data-animation-in="slideInUp"
                  data-animation-out="fadeOut"
                  data-max-width="680px"
                  data-position="right">
                <a id="demosMegaMenu" class="nav-link u-header__nav-link u-header__nav-link-toggle" href="javascript:;" aria-haspopup="true" aria-expanded="false">Offer</a>

                <!-- Demos - Mega Menu -->
                <div class="hs-mega-menu w-100 u-header__sub-menu" aria-labelledby="demosMegaMenu">
                  <div class="row no-gutters">
                    <div class="col-md-6">
                      <!-- Promo Item -->
                      <div class="u-header__promo-item">
                        <a class="u-header__promo-link" href="{% url 'app:portal' %}">
                          <div class="media align-items-center">
                            <img class="js-svg-injector u-header__promo-icon" src="{% static 'assets/svg/icons/icon-5.svg' %}" alt="SVG">
                            <div class="media-body">
                              <span class="u-header__promo-title">Internet portals</span>
                            </div>
                          </div>
                        </a>
                      </div>
                      <!-- End Promo Item -->

                      <!-- Promo Item -->
                      <div class="u-header__promo-item">
                        <a class="u-header__promo-link" href="{% url 'app:shop' %}">
                          <div class="media align-items-center">
                            <img class="js-svg-injector u-header__promo-icon" src="{% static 'assets/svg/icons/icon-52.svg' %}" alt="SVG">
                            <div class="media-body">
                              <span class="u-header__promo-title">Internet shops</span>
                            </div>
                          </div>
                        </a>
                      </div>
                      <!-- End Promo Item -->

                      <!-- Promo Item -->
                      <div class="u-header__promo-item">
                        <a class="u-header__promo-link" href="{% url 'app:on_page_website' %}">
                          <div class="media align-items-center">
                            <img class="js-svg-injector u-header__promo-icon" src="{% static 'assets/svg/icons/icon-40.svg' %}" alt="SVG">
                            <div class="media-body">
                              <span class="u-header__promo-title">One-page websites</span>
                            </div>
                          </div>
                        </a>
                      </div>
                      <!-- End Promo Item -->
					  
                      <!-- Promo Item -->
                      <div class="u-header__promo-item">
                        <a class="u-header__promo-link" href="{% url 'app:e_marketing' %}">
                          <div class="media align-items-center">
                            <img class="js-svg-injector u-header__promo-icon" src="{% static 'assets/svg/icons/icon-7.svg' %}" alt="SVG">
                            <div class="media-body">
                              <span class="u-header__promo-title">E-marketing</span>
                            </div>
                          </div>
                        </a>
                      </div>
                      <!-- End Promo Item -->
                    </div>

                    <!-- Promo -->
                    <div class="col-md-6 u-header__promo">
                      <a class="d-block u-header__promo-inner" href="{% url 'en_realization:realization' "banking-products-comparison-viewer" %}">
                        <div class="position-relative">
                          <img class="img-fluid rounded mb-3" src="{% static 'assets/img/380x270/img16.jpg' %}" alt="Image Description">
                          <span class="badge badge-success badge-pill badge-pos shadow-sm mt-3">NEW</span>
                        </div>
                        <span class="text-secondary font-size-1">Every month we present one project in detail created for our client. Read more!</span>
                      </a>
                    </div>
                    <!-- End Promo -->
                  </div>
                </div>
                <!-- End Demos - Mega Menu -->
              </li>
              <!-- End Demos -->
              
              <!-- Reference -->
              <li class="nav-item u-header__nav-item">
                <a class="nav-link u-header__nav-link" href="{% url 'en_blog:post_list' %}">Newsletter</a>
              </li>
              <!-- End Reference -->
			  
              <!-- Contact -->
              <li class="nav-item u-header__nav-item">
                <a class="nav-link u-header__nav-link" href="{% url 'app:contact' %}">Contact</a>
              </li>
              <!-- End Contact -->
              
              <li class="nav-item u-header__nav-item">
                <div class="position-relative">
                  <a class="nav-link u-header__nav-link" href="{% url 'app:home' %}">
                    <img class="dropdown-item-icon" src="{% static 'assets/vendor/flag-icon-css/flags/4x3/pl.svg' %}" alt="TG Website Language">
                    <span class="d-sm-inline-block">PL</span>
                  </a>
                </div>
              </li>

              <!-- Button -->
              <li class="nav-item u-header__nav-last-item">
                <a class="btn btn-sm btn-primary transition-3d-hover" href="{% url 'app:valuation' %}">
                  Contact sales
                </a>
              </li>
              <!-- End Button -->
            </ul>
          </div>
          <!-- End Navigation -->
        </nav>
        <!-- End Nav -->